//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('BudgetTracker')
export class BudgetTrackerEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  User: number;

  @Column('real', { nullable: true })
  BudgetAmount: number;

  @Column('real', { nullable: true })
  CurrentSpending: number;

  @Column('real', { nullable: true })
  RemainingBudget: number;

  @Column('text', { nullable: true })
  RecommendedProducts: string;
}
