//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('DietaryPreferences')
export class DietaryPreferencesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  RecommendedProducts: string;

  @Column('text', { nullable: true })
  Restrictions: string;
}
