//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ListHistory')
export class ListHistoryEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ShoppingList: number;

  @Column('date', { nullable: true })
  Date: Date;

  @Column('text', { nullable: true })
  ProductsAdded: string;

  @Column('text', { nullable: true })
  ProductsRemoved: string;

  @Column('text', { nullable: true })
  Notes: string;
}
