//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PriceComparison')
export class PriceComparisonEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  ProductName: string;

  @Column('text', { nullable: true })
  Brand: string;

  @Column('integer', { nullable: true })
  Quantity: number;

  @Column('real', { nullable: true })
  Price: number;

  @Column('real', { nullable: true })
  Quality: number;

  @Column('real', { nullable: true })
  UserRating: number;

  @Column('text', { nullable: true })
  UserExperience: string;
}
