//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('UserAccount')
export class UserAccountEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Username: string;

  @Column('text', { nullable: true })
  Email: string;

  @Column('text', { nullable: true })
  Password: string;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  ProfilePicture: string;

  @Column('integer', { nullable: true })
  ShoppingLists: number;

  @Column('integer', { nullable: true })
  DietaryPreferences: number;

  @Column('integer', { nullable: true })
  History: number;

  @Column('real', { nullable: true })
  Budget: number;

  @Column('text', { nullable: true })
  Theme: string;
}
