//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const UserAccountTitle = () => {
  const record = useRecordContext();
  return <span>UserAccount {record ? `"${record.Username}"` : ''}</span>;
};

export const UserAccountList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="Username" />
      <EmailField source="Email" />
      <ReadOnlyPasswordField source="Password" />
      <TextField source="Name" />
      <ImageField source="ProfilePicture" />
      <ReferenceField source="ShoppingLists" reference="Shoppinglist" />
      <ReferenceField
        source="DietaryPreferences"
        reference="Dietarypreferences"
      />
      <ReferenceField source="History" reference="Listhistory" />
      <NumberField source="Budget" />
      <TextField source="Theme" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const UserAccountEdit = () => (
  <Edit title={<UserAccountTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Username" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="Password" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Name" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="ProfilePicture" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ShoppingLists" reference="Shoppinglist" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="DietaryPreferences"
            reference="Dietarypreferences"
          />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="History" reference="Listhistory" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Budget" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Theme" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const UserAccountCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Username" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="Password" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Name" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="ProfilePicture" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ShoppingLists" reference="Shoppinglist" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="DietaryPreferences"
            reference="Dietarypreferences"
          />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="History" reference="Listhistory" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Budget" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Theme" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="ShoppingLists"
    label="ShoppingLists"
    reference="Shoppinglist"
    alwaysOn
  />,
  <ReferenceInput
    source="DietaryPreferences"
    label="DietaryPreferences"
    reference="Dietarypreferences"
    alwaysOn
  />,
  <ReferenceInput
    source="History"
    label="History"
    reference="Listhistory"
    alwaysOn
  />,
  ,
  ,
];
