//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Grocery Finder" />
    <CardContent>
      a project as a grocery finder with pages for essential items, shopping
      lists, price comparison, dietary preferences, nearby grocery stores, user
      account, history of lists, expiration date reminder, budget tracker, and
      dark or light mode option.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
